### ISSUE TITLE
Some small issues

### ISSUE THREAD

**Issue by felixsam359** [The-Bow-Hunter/VirusTotalDiscordBot#2]
Bot is working very well. Some small problems that I encountered.
1/ bot reacts if another bot sends an embed. It's better if it doesn't get triggers when another bot sends a message.

2/ bot scans harmless files with extension like .jpg .PNG etc.
It's better if the bot scans potentially malicious extension like .exe. Virus total API key can be used max 4 times per minute and has a monthly limit so no need to scan the pictures files.

Another enhancement feature if possible
Change the embed color to green if URL or file is safe

And change embed color to red if the URL is dangerous.

**Comment by The-Bow-Hunter** [comment]
Nice ideas. Putting that on my list, and will work on that soon

**Comment by The-Bow-Hunter** [comment]
@felixsam359 just ensure that you have the latest version of discord.py, download my changes and test it (u might want to change the settings first)
